[package]
name = "easy-rpc"
version = "0.1.0"
edition = "2024"

[features]
default = []
test = []

[dependencies]
easy-rpc-macros = { path = "./easy-rpc-macros" }
anyhow = "1.0.99"
jsonrpsee = { version = "0.26", features = ["server", "macros", "client"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.143"
schemars = "1.0.4"

[dev-dependencies]
easy-rpc = { path = ".", features = ["test"] }
